default: "prod"

prod:
  cchq_url: "https://www.commcarehq.org"
  connect_url: "https://connect.dimagi.com"
  hq_username: "debmalya.ghosal@moolya.com"
  hq_password: "Test@123"
  appium_local_url: "http://127.0.0.1:4723"
  browserstack_url: "https://hub-cloud.browserstack.com/wd/hub"

stage:
  cchq_url: ""
  connect_url: ""
  hq_username: ""
  hq_password: ""
  mobile_user: ""
  mobile_pin: ""
