default: "prod"

prod:
  cchq_url: "https://www.commcarehq.org"
  connect_url: "https://connect.dimagi.com"
  hq_username: "debmalya.ghosal@moolya.com"
  hq_password: "Test@123"

  mobile_country_code: "+7426"
  mobile_num: "7426000"
  mobile_backup_code: "742600"
  mobile_username: "Deb Test 8/12"

stage:
  cchq_url: ""
  connect_url: ""
  hq_username: ""
  hq_password: ""
  mobile_user: ""
  mobile_pin: ""
